name: Lint
on: 
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4.2.2
        - name: Use Node.js 
          uses: actions/setup-node@v4
        - name: Installing packages
          run: npm ci
        - name: Run ESLint
          run: npm run lint